### ISSUE TITLE
Please add a mac release, its not that hard.

### ISSUE THREAD

**Issue by FireDasher2** [quasar098/midi-playground#83] opened 2024-03-27 23:59 UTC
Hi, this game looks really cool.
Just so you know, i am forced to use macos, i would’ve gotten a windows if i could.
I tried to use it with whisky (app that runs windows things on mac), but it didnt work and keeps throwing openGL error.
### **So could you just please add a mac release 🙏**

**Comment by quasar098** [comment] 2024-03-28 01:03
"it's not that hard"

pyinstaller bundles the python files so that it works on the operating system that you are currently running, so i would need to be running macos

i do not want to spend 1000+ on a mac that i will use once specifically for this project

to me, getting enough money to waste 1000+ on a mac comfortably is pretty hard

additionally, macos is proprietary garbage, just use a linux vm or something; it works fine (supposedly) on linux

also duplicate of https://github.com/quasar098/midi-playground/issues/69

it is truly unfortunate you are forced to use macos

**Comment by quasar098** [comment] 2024-03-28 01:03
just use the source code (untested on mac) if you really really want it

**Closed by quasar098** 2024-03-28 01:03 UTC

**Comment by quasar098** [comment] 2024-03-28 01:04
recently a fix https://github.com/quasar098/midi-playground/pull/73 for running this on macos, so try it

**Comment by FireDasher2** [comment] 2024-03-29 15:56
OMG IT WORKeD

**Comment by FireDasher-alt** [comment] 2025-03-22 19:47
Ok yes i made this forever ago, mac is grarbage

**Comment by quasar098** [comment] 2025-03-22 21:38
> Ok yes i made this forever ago, mac is grarbage

i am adding your github actions fork as a pr
